[package]
name = "chainbridge-cli"
version = "0.1.0"
edition = "2021"
# autohr = 'davirain.yin@gmail.com'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
hex = "0.4.3"
anyhow = "1.0.65"